[package]
name = "orpheus"
version = "0.1.0"
authors = ["Nimrod Shneor <nshneor@redhat.com>"]
edition = "2018"

[dependencies]
clap = "~2.31.2"
hyper = "0.13.0"
tokio = { version = "0.2", features = ["full"] }